fix(gpu): if CUDA is unavailable raise error rather than create warning (#56)
Currently, when running TEST_GPU on a system that does not support GPU
jobs, the TEST_GPU script still proceeds with the test after concluding
that CUDA is not available:
```
CUDA is not available on this system.
[...]
in gpu_computation
    x = torch.rand(size, size, device='cuda')
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an
NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
```
The error would be more clear if we fail fast and just raise an
exception when CUDA is not available.

---------

Co-authored-by: Adam Talbot <12817534+adamrtalbot@users.noreply.github.com>